-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.account
(
    id uuid NOT NULL,
    customer_id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT account_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.purchased_software
(
    id uuid NOT NULL,
    software_id uuid NOT NULL,
    quantity integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    valid_to timestamp without time zone NOT NULL,
    account_id uuid NOT NULL,
    state integer NOT NULL,
    CONSTRAINT purchased_software_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.test
(
    id integer NOT NULL,
    text character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT test_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT account_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.purchased_software
    ADD CONSTRAINT purchased_software_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;